Update varun_generate_release_notes.yml

diff --git a/.github/workflows/varun_generate_release_notes.yml b/.github/workflows/varun_generate_release_notes.yml
--- a/.github/workflows/varun_generate_release_notes.yml
+++ b/.github/workflows/varun_generate_release_notes.yml
@@ -53,19 +53,17 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.SUNIL1_TOKEN }}
         run: |
-           if [ -z "$GITHUB_TOKEN" ]; then
-           echo "Error: GITHUB_TOKEN is empty. Please check your repository secret VARUN1_TOKEN."
-          exit 1
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "Error: GITHUB_TOKEN is empty. Please check your repository secret VARUN1_TOKEN."
+            exit 1
           fi
 
           echo "Creating tag ${TAG_NAME}"
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${REPO}.git
-
           git tag -a "${TAG_NAME}" -m "Tag created for ${PR_TITLE}"
           git push origin "${TAG_NAME}"
-
 
       - name: Create Release with Auto Notes
         env:
